######################################################################
# Automatically generated by qmake (3.0) sex out 16 20:25:57 2015
######################################################################

TEMPLATE = app
TARGET = CryptoChat
INCLUDEPATH += .
QT += widgets core

# Input
HEADERS += crypto.hpp UI/cryptochat_ui.hpp
SOURCES += crypto.cpp main.cpp UI/cryptochat_ui.cpp
